# -*- coding: utf-8 -*-
"""Pizza_Order_System_(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xXqQBVt-8VcC_ZP7KNaMwjVt8uCjsvWi
"""

#Welcome to Pizza Order System!

#İlgili Kitaplıkları İçe Aktarıyoruz.

import csv

from datetime import datetime

#menu.txt dosyası oluşturuyoruz ve okumasını sağlıyoruz.

menu_file = open("menu.txt", "r")

content = menu_file.read()
menu_file.close()

#menu.txt dosyasını yazdırıyoruz.

print(content)

#menu_file.close()

#Pizza üst sınıflarını oluşturuyoruz.

class Pizza:
    def get_description(self):
      return self.__class__.__name__
        
    def get_cost(self):
      return self.__class__.cost

#Pizza alt sınıflarını oluşturuyoruz.

class KlasikPizza(Pizza):
    cost = 60.0

    def __init__(self):
      self.description = "Klasik Pizza Malzemeleri: Peynir, Sosis, Sucuk"
      print(self.description +"\n")

class MargaritaPizza(Pizza):
    cost = 80.0
    def __init__(self):
      self.description = "Margarita Pizza Malzemeleri: Mozeralla, Domates, Fesleğen"
      print(self.description +"\n")

class TurkPizza(Pizza):
    cost = 120.0

    def __init__(self):
      self.description = "Türk Pizza Malzemeleri: Kaşar, Kuşbaşı, Biber, Soğan"
      print(self.description +"\n")

class SadePizza(Pizza):
  cost = 50.0

  def __init__(self):
    self.description = "Sade Pizza Malzemeleri: Mozerella, Kekik"
    print(self.description + "\n")

#Decorator üst sınıflarını oluşturuyoruz.

class Decorator(Pizza):
    def __init__(self, topping):
      self.component = topping

    def get_cost_sos(self):
      return self.component.get_cost() + \
          Pizza.get_cost(self)

class Zeytin(Decorator):
  cost = 5.0

  def __init__(self, topping):
    Decorator.__init__(self, topping)

class Mantarlar(Decorator):
  cost = 10.0

  def __init__(self, topping):
    Decorator.__init__(self, topping)

class KeciPeyniri(Decorator):
  cost = 15.0

  def __init__(self, topping):
    Decorator.__init__(self, topping)

class Et(Decorator):
  cost = 20.0

  def __init__(self, topping):
    Decorator.__init__(self, topping)

class Sogan(Decorator):
  cost = 3.0

  def __init__(self, topping):
    Decorator.__init__(self, topping)

class Misir(Decorator):
  cost = 8.0

  def __init__(self, topping):
    Decorator.__init__(self, topping)

#main fonksiyonu oluşturup menüyü ekrana yazdırıyoruz. Ardından input verilerini girerek sipariş için Orders_Database.csv tablosunu oluşturuyoruz.

def main():
  with open("menu.txt") as menu_liste:
      for i in menu_liste:
          print(i, end="")

  class_dict = {1: KlasikPizza, 
                2: MargaritaPizza, 
                3: TurkPizza, 
                4: SadePizza, 
                5: Zeytin, 
                6: Mantarlar, 
                7: KeciPeyniri, 
                8: Et, 
                9: Sogan, 
                10: Misir}

  code = input("Pizza Tabanı Seçiniz: ")
  if code in ["1", "2", "3", "4"]:
    order_item = class_dict[int(code)]()
    pizza_taban = order_item

  code = input("Sos Seçimi Yapınız: ")
  if code in ["5","6","7","8","9","10"]:
    order_item = class_dict[int(code)](order_item)
    pizza_sos = order_item

  print("\n"+order_item.get_description().strip() + "; $" + str(order_item.get_cost()))
  print("\n")
  print("\n"+ "Toplam:" + "; $" + str(order_item.get_cost_sos()))
  print("----------Sipariş Bilgileri----------\n")
  name = input("Adınız: ")
  surname = input("Soyadınız: ")
  ID = input("TC Kimlik Numaranız: ")
  kk_no = input("Kredi Kartı Numaranızı Giriniz: ")
  kk_psw = input("Kredi Kartı Şifrenizi Giriniz: ")
  time_of_order = datetime.now()

  with open('Orders_Database.csv', '+a') as orders:
      orders = csv.writer(orders, delimiter=',')
      orders.writerow([name, ID, kk_no, kk_psw,pizza_taban.get_description(),pizza_sos.get_description(),order_item.get_cost_sos(), time_of_order])
  print("Siparişiniz Onaylandı.")

main()